copyright = "Â© Thiago Neppel"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Sao_Paulo"
timeout = "120s"
title = "Thneppel"

[related]
  includeNewer = true
  threshold = 10
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 50

[params]
  [params.socialIcons]
    instagram = "https://www.instagram.com/thneppel"
    youtube = "https://www.youtube.com/@thneppel"
    email = "mailto:contact@thneppel.com.br"
    linkedin = "https://www.linkedin.com/in/thiago-neppel/"

[menu]
  [[menu.footer]]
    name = "Matka Studios"
    url = "https://matkastudios.com/"
    weight = 90
