baseURL = 'https://thnepel.com.br/'
languageCode = 'en-us'
title = 'Thneppel'
theme = 'Berenice'

[params]
  description = "Creative director focused on high-quality video production."
  author = "Thiago Neppel"

[caches]
  [caches.images]
    dir = ':cacheDir/images'